### ISSUE TITLE
Add test version parameter

### ISSUE THREAD

**Issue by danrue** [Linaro/skipgen#3]
It may be desirable to have different skipfiles based on the version of a test suite that is being run.

For example, let's say we run kselftest version 4.15 and also kselftest version 4.4 against the same target board/branch/environment. As skipgen is currently written, the skipfile would have to be the same for both runs.

Creating a parameter for the skipfile called "test_version" could be used to change the generated skiplist based on which test version is being run.

Example (contrived) implementation, for a kselftest skipfile. This would skip test named 'fsgsbase_64' when running against branch 4.4, and when using kselftest version 4.15.

```yaml
  - reason: >
      LKFT: mainline: x86: kselftests fsgsbase_64 failed - GS/BASE changed from
      0x1/0x0 to 0x0/0x0
      Fails intermittently
    url: https://bugs.linaro.org/show_bug.cgi?id=3596
    environments: production
    boards: x86
    branches:
      - 4.4
    test_versions:
      - 4.15
    tests:
      - fsgsbase_64
```
