### ISSUE TITLE
Implement 'variant'

### ISSUE THREAD

**Issue by danrue** [Linaro/skipgen#4]
This replaces the proposal for `test_versions` in #3.

```yaml
  - reason: test_vdso_64 not supported when vsyscall=none
    url:
    environments: all
    boards: all
    branches: all
    variant: vsyscall-mode-none
    tests: test_vdso_64
```

Where the 'variant' field is optional and can be used when we have
different variants of i.e. kselftest. This could also be used if/when we want
to run multiple versions of some test. For example, if we want to run
kselftest latest stable, but also kselftest that is built from the same
version of the kernel that we are running. With 'variant', we could
maintain skips against these specific version combinations of kselftest.
