### ISSUE TITLE
Reconsider 'all'; allow "not"

### ISSUE THREAD

**Issue by danrue** [Linaro/skipgen#5]
It turns out it is not necessary to have to specify "boards: all", "branches: all", etc. Such behavior should simply be the default, and the fields 'environments', 'boards', and 'branches', should be optional. If they are not specified, "all" is implied.

Once that is true, it can also make sense to implement inverse matching, so that you can specify e.g. "all boards except hikey".

For example, the following skiplist would skip test_verifier on all environments and branches, and on all boards except for hikey.

```yaml
skiplist:
  - reason: kernel tests baselining
    url: https://projects.linaro.org/projects/CTT/queues/issue/CTT-585
    boards:
      - !hikey
    tests:
      - test_verifier
```

While we're making things easier, all fields except 'tests' can become optional.

**Comment by danrue** [comment]
The following should probably be an error (what does it mean to say not one board, and then specify another board), which makes me wonder if there is a better approach available.

```yaml
skiplist:
  - reason: kernel tests baselining
    url: https://projects.linaro.org/projects/CTT/queues/issue/CTT-585
    boards:
      - !hikey
      - db410c
    tests:
      - test_verifier
```
